id: ID0C486DC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:48:00+00:00'
last_modified: '2022-06-08T03:08:44.008246+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9977
  title: གསང་བདེ་འཇིགས་གསུམ་སོ་སོ་དང་འབྲེལ་བའི་རབ་ཏུ་གནས་པའི་ཆོ་ག་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F6F0:
      image_group_id: I1KG9979
      title: ''
      total_pages: 302
      order: 1
      base_file: F6F0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
