id: P005446
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:50:57.470453
source_metadata:
  id: bdr:W1KG9977
  title: གསང་བདེ་འཇིགས་གསུམ་སོ་སོ་དང་འབྲེལ་བའི་རབ་ཏུ་གནས་པའི་ཆོ་ག་སོགས།
  author: ''
  volumes:
    646dc4cbbf2c4a0c89c9b070a200930a:
      image_group_id: I1KG9979
      title: ''
      volume_number: 1
      total_pages: 302
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
